name: Swift
on: [push]
jobs:

  macos:
    name: macOS
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: swift build -c debug
    - name: Build (Release)
      run: swift build -c release
    - name: Test (Debug)
      run: swift test -c debug
  
  linux:
    name: Linux
    strategy:
      matrix:
        container: ["swift:6.0.3", "swift:6.1.1", "swiftlang/swift:nightly"]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}-jammy
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: swift build -c debug
    - name: Build (Release)
      run: swift build -c release
    - name: Test (Debug)
      run: swift test -c debug

  linux-android:
    strategy:
      fail-fast: false
      matrix:
        swift: ['6.1', 'nightly-6.2']
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package on Android"
        uses: skiptools/swift-android-action@v2
        with:
          swift-version: ${{ matrix.swift }}